`try` catches exception and passes it to `except`.
`except` compares the exception type and decide whether to run following codes.
